# Generated by Django 5.2.10 on 2026-01-15 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='membre',
            name='id_association',
        ),
        migrations.AddField(
            model_name='association',
            name='desc_association',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='num_siret',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='association_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associations', to='api.associationtype'),
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id_mandat', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('president', 'Président'), ('vice_president', 'Vice-président'), ('tresorier', 'Trésorier'), ('secretaire', 'Secrétaire'), ('membre', 'Membre')], max_length=50)),
                ('statut', models.CharField(choices=[('active', 'Actif'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='active', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats', to='api.association')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats', to='api.membre')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='associations',
            field=models.ManyToManyField(related_name='membres_via_mandat', through='api.Mandat', to='api.association'),
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_types_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='member_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.membertype'),
        ),
    ]
