# Generated by Django 5.2.10 on 2026-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_roletype_remove_membre_member_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='email',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='tel',
        ),
        migrations.AddField(
            model_name='typedocument',
            name='expire_si_changement_president',
            field=models.BooleanField(default=False, help_text='Si vrai, le document expire automatiquement lors du changement de président'),
        ),
        migrations.AlterField(
            model_name='association',
            name='desc_association',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='insta_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='association',
            name='num_siret',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='association',
            name='tel_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='association',
            name='ufr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='associationtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='commentaire_refus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
