# Generated by Django 5.2.11 on 2026-02-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_membre_email_remove_membre_tel_and_more'),
        ('api', '0005_typedocument_expire_si_changement_president'),
    ]

    operations = [
    ]
