events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  # Redirection HTTP → HTTPS
  server {
    listen 80;
    server_name 91.171.53.72;
    return 301 https://$server_name$request_uri;
  }
  server {
    listen 443 ssl;
    http2 on;
    server_name 91.171.53.72;

    # Certificats SSL
    ssl_certificate /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

    # Paramètres de sécurité SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # En-têtes de sécurité
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri /index.html;
    }

    location /static/ {
      alias /static/;
      access_log off;
      expires 30d;
    }

    location /media/ {
      alias /media/;
    }

    location /api/ {
      proxy_pass http://backend:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
