sonar.projectKey=Urgaar_gestion_vie_associative
sonar.organization=mariegoupille

sonar.sources=backend,frontend/src
sonar.exclusions=**/migrations/**,**/node_modules/**

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
